4주차 필수과제!
IN-SOPT-ANDROID/sumin-bae pull request #5
Opened 2022-11-18 14:24 UTC by waterminn

2022-11-21 10:23 UTC, KWY0218 requested changes
패키징까지... 작업하시느라 고생하셨습니다 ! ! ! 👍
viewmodel 에서 통신하는 것을 리뷰 달고 싶지만 
이번 세미나 과제에 있으니까 그 때 더 자세히 달게요 ! ! !

2022-11-21 10:23 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/ApiFactory.kt
> +            .baseUrl("http://3.39.169.52:3000/")
보안을 위해서 base url을 `local properties` 로 숨기는 방식을 공부해 보는 것을 추천드립니다 !

2022-11-21 10:23 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/local/SeminarApp.kt
> +    }
이전에 문서에서 봤었는데, 어디서 봤는지 까먹어서 문서 url을 못 올리지만..
companion object는 보통 코드 최하단에 적는 것이 컨벤션입니다 !

또, application 파일은 보통 data 패키지에 만들지 않고, main 쪽에 주로 만듭니다..!

2022-11-21 10:23 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/RequestLoginDto.kt
> +    @SerialName("password") val password: String
변수 이름과 JSON 속성 이름이 일치할 때 @SerialName 을 굳이 안 붙여도 값이 들어옵니다.

2022-11-21 10:23 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/ResponseFollowerListDto.kt
> +    val per_page: Int,
```suggestion
    @SerialName("per_page")
    val perPage: Int,
```
저는 이렇게 코틀린 컨벤션과 json 속성 이름이 다를 경우에 `@SerialName` 을 사용하곤 합니다..!

2022-11-21 10:23 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/FollowerService.kt
> +    fun getList(
`getList` 변수명은 다소 불명확하다고 생각이 듭니다..!
`getUsers`, `getUserList` 등과 같이 어떤 행위를 하는지, 보는 사람이 이해할 수 있는 함수명을 지어주세요 !

2022-11-21 10:23 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/ResponseFollowerListDto.kt
> +        val last_name: String,
코틀린 컨벤션은 카멜 케이스 입니다 ! ! !

2022-11-21 10:23 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/main/follower/FollowerFragment.kt
> +                        binding.rvFollowers.adapter = adapter
통신을 할 때마다 adapter를 계속 적용하는 것 같습니다.
adapter 적용하는 함수를 따로 만들어서 한번만 설정하는 것이 좋을 것 같습니다

2022-11-21 10:23 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/ResponseFollowerListDto.kt
> +    data class Data(
Data 말고, Follower 라고 하는 것이 더 명확할 것 같습니다 !

2022-11-21 10:23 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/login/LoginActivity.kt
> +        val inputPw = binding.etLoginPw.text
해당 변수는 버튼을 클릭했을 때에만 필요하므로
onCreate에 변수로 만들지 말고, btnLoginSumit.setOnClickListener 스코프 안에 만드는 것이 더 좋을 것 같습니다 !

2022-11-21 10:34 UTC, KWY0218 commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
annotationProcessor 의 경우 자바의 어노테이션 프로세싱 툴입니다.
코틀린의 어노테이션 프로세싱 툴인 kapt를 쓰는 게 좋을 것 같습니다.

2022-11-21 10:43 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/data/local/PreferenceUtil.kt
> +}
Shared Preference 관련 함수들 공용으로 만들어둔 거 너무 좋네요 👍👍

2022-11-21 11:04 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/login/LoginActivity.kt
> +                        intentToHome(response.body()!!.result.name)
`!!`을 쓰는 건 위험하다고 생각하는데 `?`나 null check을 하는 쪽으로 수정하는 건 어떨까요?

2022-11-21 11:11 UTC, b1urrrr approved these changes
과제 하시느라 고생하셨습니다~

2022-11-21 11:11 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/main/mypage/MyPageFragment.kt
> +            }
`""`로 초기화하는 대신에 PreferenceUtil에 `clear()` 하는 함수를 만들어서 활용하는 건 어떨까요?

2022-11-21 16:10 UTC, YuBeen-Park approved these changes
과제부터 솝커톤까지 수고했어용~~!~!

2022-11-21 16:10 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/data/local/PreferenceUtil.kt
> +}
함수 모아두는 센스~~ 배워갑니다!!

2022-11-21 16:10 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/signup/SignUpActivity.kt
> +
이렇게 함수 정리할 수 있군용! 저도 코드 깔끔하게 정리하겠습니다!!

2022-11-29 08:31 UTC, waterminn commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
오오 그런 차이가 있었군요...!

2022-11-29 08:52 UTC, waterminn commented on app/src/main/java/org/sopt/sample/data/local/SeminarApp.kt
> +    }
아하...! 패키징에 대해 더 찾아봐야겠군요🤔 `companion object` 위치도 수정하겠습니당!

2022-11-29 08:57 UTC, waterminn commented on app/src/main/java/org/sopt/sample/data/remote/ApiFactory.kt
> +            .baseUrl("http://3.39.169.52:3000/")
호오 함 써볼게요 새로운 내용 알아갑니다~~!

2022-11-29 10:17 UTC, waterminn commented on app/src/main/java/org/sopt/sample/data/remote/FollowerService.kt
> +    fun getList(
앗 서두르느라 네이밍을 신경쓰지 못했네용 수정하겠습니다~!

2022-12-01 04:49 UTC, waterminn commented
@KWY0218 
좀... 많이 늦었지만 코드리뷰 전부 반영했습니다~!

2022-12-01 05:03 UTC, KWY0218 approved these changes
반영 굳 입니다 ~ ~ 👍 6주차 과제도 화이팅 ~

2022-12-01 05:05 UTC, merged