6주차 과제
IN-SOPT-ANDROID/sumin-bae pull request #6
Opened 2022-12-02 14:44 UTC by waterminn

pr 코멘트 수정중...

2022-12-03 08:09 UTC, KWY0218 requested changes
작업하시느라 수고하셨습니다 ! ! ! 👍

2022-12-03 08:09 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginActivity.kt
> +        val binding = ActivityLoginBinding.inflate(layoutInflater)
binding을 onCreate 에 선언하면 binding과 관련한 로직은 모두 onCreate에 밀집 할 것이고,
그렇게 된다면 onCreate 안에 코드량이 많아져서 가독성이 떨어질 것입니다.
다시 lateinit var로 수정하고, onCreate에 선언한 로직들을 함수로 분리한다면 가독성이 좋아질 것입니다!

2022-12-03 08:09 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginActivity.kt
>          }
이미 viewmodel에서 `isSuccessful` 일 때 loginResult 값을 바꿔주고 있기 때문에
if 문 로직은 코드 중복인 것 같습니다.

2022-12-03 08:09 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginViewModel.kt
> +                    }
400 이상인 코드는 모두 `onFailure`로 가기 때문에 없어도 되는 로직 같아 보입니다

2022-12-03 08:09 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginViewModel.kt
> +                        _errorMessage.value = "아이디 또는 비밀번호를 잘못 입력했습니다"
그렇기 때문에 해당 if문을 없애고, value 값만 설정하는 로직만 남아도 될 것 같습니다

2022-12-03 08:09 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginViewModel.kt
> +                    }
로그인 통신 결과가 성공한 이후에 loginResult value 값을 변경하고 있고,
activity에서는 이 loginResult 변수를 observe 하고 있습니다.

하지만 통신 성공 후 로직은 응답 값인 body 값은 activity에서 사용하지 않고, 
viewmodel에서 내부 저장소에 값을 저장하는 로직만 있습니다.

그래서 저는 loginResult 에 꼭 body 값이 안 들어가고, boolean 값이 들어가도 될 것 같다는 생각이 듭니다.

2022-12-03 08:09 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginViewModel.kt
> +        get() = _errorMessage
개인적으로 저는 error 메시지를 viewmodel에서 전달하는 것이 아닌, viewmodel에서 activity에게 신호를 주고
이 신호를 관찰하는 activity가 viewmodel의 신호에 따라서 error 메시지를 보여주는 로직이 좀 더 선호합니다.

왜냐하면 error 메시지의 내용은 토스트로 띄울 건데 토스트는 ui 관련이니 viewmodel에 error 메시지 값이 있으면 어색하다고 생각하기 때문입니다 ... ㅎㅎ..

하지만 서버 통신 응답은 200일 때, 400일 때, 500일 때 등 다양한데, boolean 값은 2가지 밖에 구분하지 못해서 한계가 있습니다.

그래서 enum class 또는 sealed class를 이용해서 이를 구분하는 방식으로 리팩토링 하는 것을 추천드립니다..!

2022-12-03 08:09 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/main/follower/FollowerFragment.kt
> +        viewModel.getUserList()
해당 onViewCreated 로직 내부도 함수로 분리하는 것을 추천드립니다!

2022-12-03 08:09 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpActivity.kt
> +        val binding = ActivitySignUpBinding.inflate(layoutInflater)
요기두 위에 내용과 동일합니다~

2022-12-03 08:09 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpViewModel.kt
> +    fun signup(id: String, password: String, name: String) {
위에 login viewmodel에 남겼던 리뷰와 같이 적용해보는 것을 추천드립니다

2022-12-03 08:09 UTC, KWY0218 commented on app/src/main/res/layout/activity_sign_up.xml
> +            type="org.sopt.sample.presentation.signup.SignUpViewModel" />
sign up 보다, vm, viewmodel 같은 네이밍이 좀 더 자연스러울 것 같습니다

2022-12-03 08:09 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpViewModel.kt
> +    val inputName = MutableLiveData<String>()
초기 값으로 `""` 넣어주면 들어가자마자 빨간 줄 뜨는 오류 해결할 수 있을 것 같습니다~

2022-12-03 08:09 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/main/MainActivity.kt
> +            finish()
1. 해당 로직은 ui와 관련 없기 때문에 activity 보다 viewmodel 에 넣는 것을 추천드립니다.
2. viewmodel로 로직이 수정된다면 또 분기처리 해야 할 변수 만들고, activity에서는 observe 하는 과정이 추가될 것입니다. 그래서 저는 시작점을 main activity가 아닌 login activity로 수정하고, login viewmodel에서 로직을 구현한다면 login viewmodel에서 이미 main activity로 가게끔 신호를 주는 로직이 있으니까 코드를 재활용 하면서 구현할 수 있을 것 같습니다

2022-12-03 14:31 UTC, b1urrrr approved these changes
과제하시느라 고생하셨습니다!! 👍👍

2022-12-03 14:31 UTC, b1urrrr commented on app/src/main/res/layout/activity_sign_up.xml
> +            android:enabled="@{!signup.inputId.isEmpty() &amp;&amp; !signup.inputPw.isEmpty() &amp;&amp; signup.isValidId &amp;&amp; signup.isValidPw &amp;&amp; signup.isValidName}"
```suggestion
            android:layout_marginTop="45dp"
            android:enabled="@{signup.isValidId &amp;&amp; signup.isValidPw &amp;&amp; signup.isValidName}"
```
이미 `isValidId`랑 `isValidPw`에서 비워져있으면 false를 반환하기 때문에 `isEmpty()`는 없어도 될 것 같아요!

2022-12-03 14:31 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/main/follower/FollowerFragment.kt
> +                    else -> 1
FollowerAdapter에서 만들어놓은 `TYPE_HEADER`와 `TYPE_FOLLOWER`를 활용하는 게 가독성이 더 좋을 것 같아요!

2022-12-03 14:31 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpActivity.kt
> +        binding.lifecycleOwner = this
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-12-03 14:31 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpActivity.kt
>          }
데이터바인딩으로 버튼 onClick을 설정해주면 뷰바인딩으로 클릭 리스너를 따로 안 달아줘도 될 것 같아요!

2022-12-04 08:32 UTC, waterminn commented on app/src/main/java/org/sopt/sample/presentation/login/LoginActivity.kt
> +        val binding = ActivityLoginBinding.inflate(layoutInflater)
> binding과 관련한 로직은 모두 onCreate에 밀집 할 것이고

따로 함수를 만들 때도 binding을 못 쓰니까 더 그렇겠네요...! 다시 돌려놓겠습니당 함수도 이것저것 만들어봐야겠네요

2022-12-04 08:39 UTC, waterminn commented on app/src/main/java/org/sopt/sample/presentation/login/LoginViewModel.kt
> +                    }
서버통신이 아직 익숙하지 않다는게 전체적으로 티가 나네요...ㅎㅎ 더더 공부할게요오

2022-12-04 08:41 UTC, waterminn commented on app/src/main/java/org/sopt/sample/presentation/login/LoginActivity.kt
>          }
아앗 그러네요...!

2022-12-09 11:51 UTC, waterminn commented on app/src/main/java/org/sopt/sample/presentation/login/LoginViewModel.kt
> +        get() = _errorMessage
sealed class 사용하는걸로 해서 수정했어요! 로직이 더 직관적으로 잘 보이는 것 같아 훨씬 낫네요...!
일단 세 경우만 상태를 정해놓긴 했는데 더 늘려서 상태를 더 자세히 확인해보는 것도 좋을 것 같긴 하네요🤔

2022-12-09 11:52 UTC, waterminn commented on app/src/main/java/org/sopt/sample/presentation/main/follower/FollowerFragment.kt
> +                    else -> 1
그거 갖고오는데 실패해서 임시로 저렇게 한건데 다시 시도해볼게용!

2022-12-09 11:55 UTC, waterminn commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpActivity.kt
>          }
오오.... 수정하겠습니당!

2022-12-09 11:56 UTC, waterminn commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpViewModel.kt
> +    val inputName = MutableLiveData<String>()
해결됐어요오 감사합니다~!!

2022-12-09 11:57 UTC, waterminn commented on app/src/main/res/layout/activity_sign_up.xml
> +            type="org.sopt.sample.presentation.signup.SignUpViewModel" />
넵 데이터바인딩은 일반 변수 네이밍 컨벤션과 살짝 다른 것 같네요...!

2022-12-12 07:52 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/service/UiState.kt
> +}
이름이 `UiState` 인데 data 패키지에 있는 것이 부자연스러워 보입니다!
차라리 util 패키지에 넣는 것이 자연스러울 것 같습니다..!

2022-12-12 08:21 UTC, wateralsie commented on app/src/main/java/org/sopt/sample/data/service/UiState.kt
> +}
@KWY0218 
패키징... 방법이 가지각색이라서 쉽지 않네유😂
이건 그냥 궁금한건데 보통 util 패키지에는 어떤 것이 들어가나요?

2022-12-12 09:43 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/service/UiState.kt
> +}
저는 ui에서 자주 사용하고, 전역에서 사용하는 로직들을 util 패키지 안에 넣습니다!

2022-12-12 09:53 UTC, wateralsie commented on app/src/main/java/org/sopt/sample/data/service/UiState.kt
> +}
오옹 감사합니다!

2023-02-05 12:26 UTC, merged